# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mastery Learning in CS Education
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  We want to plant the seeds for a community of practice on Mastery Learning for Programming Courses, by making our lessons learned and resources available in an easily adoptable way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github: [metadata]


# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Theme: 
permalink: pretty

google_analytics_id: null
homepage:
  show_call_box: true
# logo:
  # mobile: "images/logo/logo-mobile.svg"
  # desktop: "images/logo/logo.svg"
  # desktop_height: "36px"
footer:
  copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

seo:
  meta_og_title: "Mastery Learning in CS Education"
  meta_og_type: "website"
  meta_og_url: "https://csmasterylearning.github.io/"
  # meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "We want to plant the seeds for a community of practice on Mastery Learning for Programming Courses, by making our lessons learned and resources available in an easily adoptable way."
  meta_twitter_card: "summary"
  meta_twitter_site: "@LuCEresearchlab"
  meta_twitter_creator: "@LuCEresearchlab"

collections:
  masteries:
    output: true
    permalink: /masteries/:path/
  team:
    output: true
    permalink: /team/:path/

defaults:
  - scope:
      type: masteries
    values:
      layout: mastery
      bodyClass: page-masteries-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-feed
  - jekyll-environment-variables
